# Stage 1: Build the application
FROM node:20-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application to the container
COPY . .

# Expose port 5173 for the Vite development server
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev", "--", "--host"]